name: Deploy VulnApp

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Outdated version
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Outdated version
    
    # Secrets in plain text
    - name: Build application
      env:
        DB_PASSWORD: admin123
        JWT_SECRET: my_jwt_secret
        AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
        AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      run: |
        npm install
        npm run build
        
    # Dangerous script execution
    - name: Run deployment script  
      run: |
        curl -sSL https://deploy.vulnapp.com/deploy.sh | bash
